#!/usr/bin/env bash
# =============================================================
# FirstLook Field Agent — Install Script
# =============================================================
# Usage (generated by the control server prep page):
#
#   curl -sSL https://your-server:8000/agent/install.sh | \
#     bash -s -- --server https://your-server:8000 \
#                --agent-id <uuid> \
#                --token <token>
#
# What this script does:
#   1. Checks prerequisites (Python 3.11+, pip, nmap, lldpd)
#   2. Installs missing system packages
#   3. Creates a dedicated system user
#   4. Installs the agent into /opt/firstlook-agent
#   5. Writes /etc/firstlook-agent/agent.conf
#   6. Installs and enables a systemd service
#   7. Starts the agent
#
# Supported distributions:
#   - Ubuntu 20.04 / 22.04 / 24.04
#   - Debian 11 / 12
#
# Requirements:
#   - Must be run as root or via sudo
#   - Internet access to reach the control server
# =============================================================

set -euo pipefail

# ─────────────────────────────────────────
# Colours
# ─────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

log()     { echo -e "${CYAN}[firstlook]${RESET} $*"; }
success() { echo -e "${GREEN}[firstlook]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[firstlook]${RESET} $*"; }
error()   { echo -e "${RED}[firstlook]${RESET} $*" >&2; }
die()     { error "$*"; exit 1; }

# ─────────────────────────────────────────
# Constants
# ─────────────────────────────────────────
AGENT_USER="root"
INSTALL_DIR="/opt/firstlook-agent"
CONFIG_DIR="/etc/firstlook-agent"
DATA_DIR="/var/lib/firstlook-agent"
SERVICE_NAME="firstlook-agent"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
AGENT_REPO_URL=""   # Populated at runtime from --server arg

# ─────────────────────────────────────────
# Parse arguments
# ─────────────────────────────────────────
SERVER_URL=""
AGENT_UUID=""
API_TOKEN=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --server)       SERVER_URL="$2";    shift 2 ;;
        --agent-id)     AGENT_UUID="$2";    shift 2 ;;
        --token)        API_TOKEN="$2";     shift 2 ;;
        *)              die "Unknown argument: $1" ;;
    esac
done

# Validate required args
[[ -z "$SERVER_URL"  ]] && die "--server is required"
[[ -z "$AGENT_UUID"  ]] && die "--agent-id is required"
[[ -z "$API_TOKEN"   ]] && die "--token is required"

AGENT_REPO_URL="${SERVER_URL}/agent/download"

# ─────────────────────────────────────────
# Banner
# ─────────────────────────────────────────
echo ""
echo -e "${BOLD}  FirstLook Field Agent — Installer${RESET}"
echo    "  ────────────────────────────────────"
echo    "  Server:     ${SERVER_URL}"
echo    "  Agent UUID: ${AGENT_UUID}"
echo    ""

# ─────────────────────────────────────────
# Root check
# ─────────────────────────────────────────
if [[ "$EUID" -ne 0 ]]; then
    die "This script must be run as root. Try: sudo bash -s -- ..."
fi

# ─────────────────────────────────────────
# OS check
# ─────────────────────────────────────────
if [[ ! -f /etc/os-release ]]; then
    die "Cannot determine OS. This script supports Ubuntu and Debian."
fi

. /etc/os-release

if [[ "$ID" != "ubuntu" && "$ID" != "debian" ]]; then
    warn "Unsupported OS: ${PRETTY_NAME}. Proceeding anyway — your mileage may vary."
fi

log "Detected OS: ${PRETTY_NAME}"

# ─────────────────────────────────────────
# System packages
# ─────────────────────────────────────────
log "Updating package lists..."
apt-get update -qq

PACKAGES=(
    python3
    python3-pip
    python3-venv
    nmap
    lldpd
    libsnmp-dev
    snmp
    curl
)

log "Installing system packages: ${PACKAGES[*]}"
apt-get install -y -qq "${PACKAGES[@]}"

# Enable lldpd so it starts broadcasting and receiving LLDP frames
log "Enabling lldpd service..."
systemctl enable lldpd --quiet
systemctl start lldpd || warn "lldpd failed to start — LLDP discovery will be unavailable"

# Grant nmap raw socket access so SYN scans work without root
log "Setting nmap capabilities..."
NMAP_BIN=$(which nmap)
if [ -n "$NMAP_BIN" ]; then
    setcap cap_net_raw,cap_net_admin+eip "$NMAP_BIN"
    success "nmap capabilities set — SYN scanning enabled"
else
    warn "nmap not found — skipping capability set"
fi

# ─────────────────────────────────────────
# Python version check
# ─────────────────────────────────────────
PYTHON_BIN=$(command -v python3)
PYTHON_VERSION=$("$PYTHON_BIN" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PYTHON_MAJOR=$(echo "$PYTHON_VERSION" | cut -d. -f1)
PYTHON_MINOR=$(echo "$PYTHON_VERSION" | cut -d. -f2)

if [[ "$PYTHON_MAJOR" -lt 3 || ( "$PYTHON_MAJOR" -eq 3 && "$PYTHON_MINOR" -lt 11 ) ]]; then
    die "Python 3.11+ is required. Found: Python ${PYTHON_VERSION}"
fi

success "Python ${PYTHON_VERSION} — OK"

# ─────────────────────────────────────────
# Create system user
# ─────────────────────────────────────────
if ! id "$AGENT_USER" &>/dev/null; then
    log "Creating system user: ${AGENT_USER}"
    useradd \
        --system \
        --no-create-home \
        --shell /usr/sbin/nologin \
        --comment "FirstLook Field Agent" \
        "$AGENT_USER"
else
    log "User ${AGENT_USER} already exists — skipping"
fi

    log "Configuring nmap sudo access..."
    echo "${AGENT_USER} ALL=(ALL) NOPASSWD: /usr/bin/nmap" /etc/sudoers.d/firstlook-nmap
    chmod 440 /etc/sudoers.d/firstlook-nmap
    success "nmap sudo access configured"

# ─────────────────────────────────────────
# Create directories
# ─────────────────────────────────────────
log "Creating directories..."
mkdir -p "$INSTALL_DIR" "$CONFIG_DIR" "$DATA_DIR"

# ─────────────────────────────────────────
# Download agent code
# ─────────────────────────────────────────
log "Downloading agent from ${AGENT_REPO_URL}..."

AGENT_ARCHIVE="/tmp/firstlook-agent.tar.gz"

if ! curl -fsSL \
    -H "Authorization: Bearer ${API_TOKEN}" \
    "${AGENT_REPO_URL}" \
    -o "$AGENT_ARCHIVE"; then
    die "Failed to download agent archive from ${AGENT_REPO_URL}"
fi

log "Extracting agent..."
tar -xzf "$AGENT_ARCHIVE" -C "$INSTALL_DIR"
rm -f "$AGENT_ARCHIVE"

# ─────────────────────────────────────────
# Python virtual environment
# ─────────────────────────────────────────
log "Creating Python virtual environment..."
"$PYTHON_BIN" -m venv "${INSTALL_DIR}/venv"

log "Installing Python dependencies..."
"${INSTALL_DIR}/venv/bin/pip" install \
    --quiet \
    --upgrade pip

"${INSTALL_DIR}/venv/bin/pip" install \
    --quiet \
    -r "${INSTALL_DIR}/requirements.txt"

success "Dependencies installed"

# ─────────────────────────────────────────
# Write config file
# ─────────────────────────────────────────
log "Writing agent config to ${CONFIG_DIR}/agent.conf..."
cat > "${CONFIG_DIR}/agent.conf" <<EOF
# FirstLook Agent Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not edit manually — re-run the install script to reconfigure.

FL_SERVER_URL=${SERVER_URL}
FL_AGENT_UUID=${AGENT_UUID}
FL_API_TOKEN=${API_TOKEN}
FL_POLL_INTERVAL=30
FL_HEARTBEAT_INTERVAL=60
FL_SCAN_THROTTLE=0.5
EOF

chmod 600 "${CONFIG_DIR}/agent.conf"
chown root:root "${CONFIG_DIR}/agent.conf"

# ─────────────────────────────────────────
# Set permissions
# ─────────────────────────────────────────
log "Setting file permissions..."
chown -R "${AGENT_USER}:${AGENT_USER}" "$INSTALL_DIR"
chown -R "${AGENT_USER}:${AGENT_USER}" "$DATA_DIR"
# Config stays root-owned, readable by root only — agent reads via env

# ─────────────────────────────────────────
# systemd service
# ─────────────────────────────────────────
log "Installing systemd service..."
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=FirstLook Field Agent
Documentation=https://github.com/firstlook-msp/firstlook
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${AGENT_USER}
Group=${AGENT_USER}

WorkingDirectory=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/venv/bin/python agent.py

Environment=PYTHONUNBUFFERED=1

# Load config as environment variables
EnvironmentFile=${CONFIG_DIR}/agent.conf

# Restart on failure with a back-off
Restart=on-failure
RestartSec=15s
StartLimitInterval=300s
StartLimitBurst=5

# Security hardening
NoNewPrivileges=no
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=${DATA_DIR}
PrivateTmp=yes

# Nmap requires raw socket access (CAP_NET_RAW)
# This is the minimum capability required for SYN scanning
AmbientCapabilities=CAP_NET_RAW CAP_NET_ADMIN
CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}" --quiet

# ─────────────────────────────────────────
# Start the agent
# ─────────────────────────────────────────
log "Starting FirstLook agent..."
systemctl start "${SERVICE_NAME}"

# Give it a moment to come up
sleep 3

if systemctl is-active --quiet "${SERVICE_NAME}"; then
    success "Agent is running."
else
    error "Agent failed to start. Check logs with:"
    error "  journalctl -u ${SERVICE_NAME} -n 50"
    exit 1
fi

# ─────────────────────────────────────────
# Done
# ─────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}  Installation complete.${RESET}"
echo    "  ──────────────────────────────────────────────"
echo    "  The agent is running and will register with:"
echo    "  ${SERVER_URL}"
echo    ""
echo    "  Useful commands:"
echo    "  Status:   systemctl status ${SERVICE_NAME}"
echo    "  Logs:     journalctl -u ${SERVICE_NAME} -f"
echo    "  Stop:     systemctl stop ${SERVICE_NAME}"
echo    "  Remove:   systemctl disable ${SERVICE_NAME} && rm -rf ${INSTALL_DIR} ${CONFIG_DIR} ${DATA_DIR}"
echo    ""
